/*
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */

#include "common.h"

namespace method1 {

char findTheDifference(string s, string t) {
  vector<int> hash('z' - 'a' + 1, 0);

  for (auto t : s) {
    hash[t - 'a']++;
  }

  for (auto t : t) {
    hash[t - 'a']--;
  }

  for(int i = 0; i < hash.size(); i++) {
    if(hash[i] != 0) {
      return 'a' + i;
    }
  }

  return ' ';
}

}

// more nice algorithm

namespace method2 {

char findTheDifference(string s, string t) {
  char result = s[0];

  for (int i = 1; i < s.size(); i++) {
    result ^= s[i];
  }

  for (auto i : t) {
    result ^= i;
  }

  return result;
}

}


int main() {
  return 0;
}

